name: DIR 1

on:
  pull_request:
    paths: ['dir1/**']
  push:
    branches: ['main']
    paths: ['dir1/**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Branch name
        run: echo ${GITHUB_REF##*/}

      - name: Step only for master
        if: github.event_name == 'push'
        run: echo 'OK'
