name: DIR 2

on:
  pull_request:
    paths: ['dir2/**']
  push:
    branches: ['master']
    paths: ['dir2/**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Branch name
        run: |
          echo ${GITHUB_REF}
          echo ${GITHUB_REF##*/}
          echo ${{ github.ref }}

      - name: Step only for master
        if: github.event_name == 'push'
        run: echo 'OK'
