name: DIR 2

on:
  pull_request:
    paths:
      - 'dir2/**'
      - '.github/workflows/dir2-changes.yaml'
  push:
    branches: ['master']
    paths:
      - 'dir2/**'
      - '.github/workflows/dir2-changes.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Branch name
        run: |
          echo ${GITHUB_REF}
          echo ${GITHUB_REF##*/}
          echo ${github.ref}

      - name: Step only for master
        if: ${{ github.ref##*/ }} == 'master'
        run: echo 'OK'
